---=========================================================---
--------------------MAGNITUDE ANALYSIS--------------------------
     --------Compares the measure values by categories----
	 -------- Analysed through MEASURE by CATEGORY--------
---=========================================================---

--Find the Total customers by countries
SELECT 
    country,
	COUNT(customer_key) customer_count
FROM gold.dim_customers
GROUP BY country
ORDER BY customer_count DESC

--Find the Total customers by gender
SELECT 
	gender,
	COUNT(customer_key) customer_count
FROM gold.dim_customers
GROUP BY gender
ORDER BY customer_count DESC

--Find he Total products by category
SELECT  
	category,
	COUNT(product_key) product_count
FROM gold.dim_products
GROUP BY category
ORDER BY product_count DESC

--What is the average cost in each category?
SELECT  
	category,
	AVG(product_cost) average_price
FROM gold.dim_products
GROUP BY category
ORDER BY average_price DESC

--What is the total revenue generate by each category?
SELECT  
	pd.category,
	SUM(sf.sales_amount) total_revenue
FROM gold.fact_sales sf
LEFT JOIN gold.dim_products pd
ON pd.product_key = sf.product_key
GROUP BY pd.category
ORDER BY total_revenue DESC

--Find the Total revenue generated by each customer?
SELECT  
	cd.customer_id,
	cd.firstname,
	cd.lastname,
	SUM(sf.sales_amount) total_revenue
FROM gold.fact_sales sf
LEFT JOIN gold.dim_customers cd
ON cd.customer_key = sf.customer_key
GROUP BY cd.customer_id,
	     cd.firstname,
	     cd.lastname
ORDER BY total_revenue DESC

--What is the distribution of sold items across the countries?
SELECT  
	cd.country,
	SUM(sf.quantity) total_items_sold
FROM gold.fact_sales sf
LEFT JOIN gold.dim_customers cd
ON cd.customer_key = sf.customer_key
GROUP BY country
ORDER BY total_items_sold DESC
